<?php

namespace MarketplaceBundle\Repository;

use MarketplaceBundle\Entity\Category;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

}
