<?php

namespace MarketplaceBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategory($id){
        $products = $this->findBy(['category'=>$id]);
    }
}
