<?php

namespace MarketplaceBundle\Repository;

/**
 * ProductstestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductstestRepository extends \Doctrine\ORM\EntityRepository
{
}
